apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: hassen2208/auth-service:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 5555
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        command: ["/wait-for-rabbitmq.sh"]
        args: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort  # Cambiado de ClusterIP a NodePort
  selector:
    app: auth-service
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
    nodePort: 30007  # Especifica un puerto entre 30000 y 32767

---
# Despliegue para RabbitMQ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672  # Puerto para comunicación AMQP
        - containerPort: 15672  # Puerto para la interfaz web de RabbitMQ
        env:  # Variables de entorno para configurar RabbitMQ
        - name: RABBITMQ_DEFAULT_USER
          value: "myuser"
        - name: RABBITMQ_DEFAULT_PASS
          value: "mypassword"

---
# Servicio para RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp  # Nombre único para el puerto AMQP
    protocol: TCP
    port: 5672  # Puerto AMQP para comunicación con clientes
    targetPort: 5672
  - name: management  # Nombre único para la interfaz de administración
    protocol: TCP
    port: 15672  # Puerto para la interfaz web de RabbitMQ
    targetPort: 15672
  type: ClusterIP  # El servicio es accesible dentro del clúster