apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: hassen2208/auth-service:latest
        command: ["/wait-for-rabbitmq.sh"]
        args: ["npm", "start"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_DEFAULT_USER
          value: "myuser"
        - name: RABBITMQ_DEFAULT_PASS
          value: "mypassword"
        - name: NODE_ENV
          value: "development"
        - name: RABBITMQ_URL
          value: "amqp://myuser:mypassword@rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
