version: '3.8'

services:
  auth-service:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - error-service

  error-service:
    image: tarampampam/error-pages
    environment:
      TEMPLATE_NAME: "lost-in-space"
      SHOW_DETAILS: true
    ports:
      - "8080:80"
