version: '3.8'

services:
  auth-service:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - error-service
    volumes:
      - logs:/var/log/auth-service

  error-service:
    image: tarampampam/error-pages
    environment:
      TEMPLATE_NAME: "lost-in-space"
      SHOW_DETAILS: true
    ports:
      - "8080:80"


  fluent-bit:
    image: fluent/fluent-bit:latest
    depends_on:
      - auth-service
    volumes:
      - logs:/var/log/auth-service
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    command: -c /fluent-bit/etc/fluent-bit.conf

volumes:
  logs:
