apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: rabbitmq-port
        - containerPort: 15672
          name: rabbitmq-manage
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "myuser"
        - name: RABBITMQ_DEFAULT_PASS
          value: "mypassword"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq-port
    - port: 15672
      targetPort: 15672
      name: rabbitmq-management-port
  selector:
    app: rabbitmq
